### PR TITLE
Update creation credits

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Review by Zhen-hao — APPROVED** [review]

**Comment by raboof** [comment]
We might also want to update the 'about' text for the repo?

**Comment by nightkr** [comment]
The about text still contains the dead link, fwiw.

(To be clear: I'm not complaining or anything, I just noticed it when I came across the repo again for other reasons.)

**Comment by raboof** [comment]
(I had a look but I'm not an admin for this repo so can't update it)

**Comment by Zhen-hao** [comment]
@nightkr Thank you for reporting. I updated the description of the repo.

**Pull request merged**
